#!/bin/bash

mkdir -p ~/bin

OPWD=$PWD; cd ~/bin

for script in ../development/bash/bashutils/*.bash; do
    [[ -f $script ]] || continue
    ln -sfvn "$script" "$(basename "$script" .bash)"
done

cd "$OPWD"
