#!/bin/bash

DIR=${1:-$HOME/bin}

mkdir -p "$DIR"

for script in "$(dirname "$0")"/*.sh; do
    [[ -f $script ]] || continue
    cp -fv "$script" "$DIR/$(basename "$script" .sh)"
done

echo "All scripts should be installed. Be sure '$DIR' is in your PATH." |
sed "s%${HOME//%/\%}%~%g"
