.TH bashful 1 "September 2010" bashful
.SH NAME
Bashful - A collection of libraries to simplify writing bash scripts
.SH SYNOPSIS
source
.B bashful
.br
source
.B bashful-execute
.br
source
.B bashful-files
.br
source
.B bashful-input
.br
source
.B bashful-messages
.br
source
.B bashful-modes
.br
source
.B bashful-profile
.br
source
.B bashful-terminfo
.br
source
.B bashful-utils
.br
.SH DESCRIPTION
.B Bashful
is a collection of bash libraries to simplify writing other bash scripts.
.P
To get complete documentation for each library, just invoke it at the command line with
.B help
as the first argument. For example, to get documentation for the
.B input
library:
.P
.RS
.B $
bashful-input help
.RE
.P
.B bashful-execute
.RS
This library provides functions for building and executing commands.
.RE
.P
.B bashful-files
.RS
This library provides functions for working with files/directories.
.RE
.P
.B bashful-input
.RS
This library provides functions for getting user input.
.RE
.P
.B bashful-messages
.RS
This library provides functions for notifying the user.
.RE
.P
.B bashful-modes
.RS
This library provides functions for getting and setting mode values (verbose, interactive).
.RE
.P
.B bashful-profile
.RS
This library provides functions for using configuration profiles.
.RE
.P
.B bashful-terminfo
.RS
This library provides functions for altering the appearance of terminal output (bold, underline, color).
.RE
.P
.B bashful-utils
.RS
This library provides miscellaneous functions.
.RE
